org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Minecraft and Forge
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.0
forge_version_range=[47.4.0,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

# Your mod - replace these values when copying the template
mod_id=arcaneempowerment
mod_name=ArcaneEmpowerment
mod_license=MIT
mod_version=0.1-1.20.1
mod_group_id=net.prismalmidu.arcaneempowerment
mod_authors=PrismAlmidu
mod_description=Uses multiblocks and a perk tree to enhance aspects of Mana and Artifice.

# Mana and Artifice and its dependencies
mna_version=3.1.11
mna_file_id=6847805
curios_version=5.6.1
curios_file_id=5066845
geckolib_version=4.4.7
geckolib_file_id=5460312

# Mana and Artifice: Attributes and its dependencies
mna_attributes_version=0.3.2
mna_attributes_file_id=7876589
apothic_attributes_version=1.3.7
apothic_attributes_file_id=5634071
placebo_version=8.6.3
